
spring:
  application:
    name: senfanoj-backend-judge-service
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.121.109:3306/senfanoj
    username: root
    password: senfan@235
  # Redis ??
  redis:
    database: 1
    host: 8.136.121.109
    port: 6379
    timeout: 5000
    password: senfan@235
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 8.136.121.109:8848
#  rabbitmq:
#    host: 8.136.121.109
#    port: 9102
#    password: senfan235
#    username: senfan@235
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api/judge
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ??????
codesandbox:
  type: remote
knife4j:
  enable: true